_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 71
            "2":
                - 1
                - 11
                - 49
                - 51
                - 71
            "3":
                - 16
                - 55
            "4": 3.11.11
            "5": 0.20.1
            "6": 4.52.4
            "8":
                - 2
            "12": 0.20.1
            "13": linux-x86_64
model_dim:
    value: 768
num_epochs:
    value: 3
num_layers:
    value: 12
vocab_size:
    value: 50257
